###Register a new user
POST http://localhost:5000/user-api/auth/signup 
Content-Type: application/json

{   
    "userType":"user",
    "username": "keli",
    "email": "keli@example.com",
    "password": "kelipassword",
    "name": "Keli",
    "phone": "+1234567890",
    "address": "keli street,abc",
    "cart":[],
    "orders":[]
}

###Register a new admin
POST http://localhost:5000/admin-api/auth/signup 
Content-Type: application/json

{
    "userType":"admin",
    "username": "admin_keli",
    "email": "keli@example.com",
    "password": "keliadmin",
    "name": "Keli",
    "phone": "+1234567890",
    "address": "keli street,abc"
}


###Sign in (Authenticate user)
POST http://localhost:5000/user-api/auth/login 
Content-Type: application/json

{
    "userType":"user",
    "username": "keli",
    "password": "kelipassword"
}

###Sign in (Authenticate admin)
POST http://localhost:5000/admin-api/auth/login 
Content-Type: application/json

{
    "userType":"admin",
    "username": "admin_keli",
    "password": "keliadmin"
}


###Get user profile
GET http://localhost:5000/user-api/users/keli
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImtlbGkiLCJpYXQiOjE3NDQ2NDgzNjh9.HeMpPNpR8YUckTulNIyfUcTeGj1dIR1F6KsBdDngzkQ


###Update user profile
PUT http://localhost:5000/user-api/users/keli
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImtlbGkiLCJpYXQiOjE3NDQ2NDgzNjh9.HeMpPNpR8YUckTulNIyfUcTeGj1dIR1F6KsBdDngzkQ

{
    "email": "newkeli@example.com"
}

###Get user’s cart
GET http://localhost:5000/user-api/users/67fd387b2dc2c72eb6d1d6fc/cart 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImtlbGkiLCJpYXQiOjE3NDQ2NDgzNjh9.HeMpPNpR8YUckTulNIyfUcTeGj1dIR1F6KsBdDngzkQ

###Add item to cart
POST http://localhost:5000/user-api/users/67fd387b2dc2c72eb6d1d6fc/cart 
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImtlbGkiLCJpYXQiOjE3NDQ2NDgzNjh9.HeMpPNpR8YUckTulNIyfUcTeGj1dIR1F6KsBdDngzkQ

{
    "artId": "67eacf83f17206741b0dcb22",
    "quantity":9999,
    "deleted":false
}

###Remove item from cart
PUT http://localhost:5000/user-api/users/67fd387b2dc2c72eb6d1d6fc/cart/67eacf83f17206741b0dcb22
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImtlbGkiLCJpYXQiOjE3NDQ2NDgzNjh9.HeMpPNpR8YUckTulNIyfUcTeGj1dIR1F6KsBdDngzkQ

###Get user’s order history(Orders Requests)
GET http://localhost:5000/user-api/users/67fd387b2dc2c72eb6d1d6fc/orders
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImtlbGkiLCJpYXQiOjE3NDQ2NDgzNjh9.HeMpPNpR8YUckTulNIyfUcTeGj1dIR1F6KsBdDngzkQ

###Place an order
POST http://localhost:5000/user-api/users/67fd387b2dc2c72eb6d1d6fc/orders 
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImtlbGkiLCJpYXQiOjE3NDQ2NDgzNjh9.HeMpPNpR8YUckTulNIyfUcTeGj1dIR1F6KsBdDngzkQ

{
    "items":[
        {
            "artsId":"67eacf83f17206741b0dcb22",
            "quantity":100
        }
    ],
    "totalPrice":50000,
    "status":"Pending",
    "orderTime":"{{$datetime iso8601}}",
    "modifyTime":"{{$datetime iso8601}}"
}


###Track Order
GET http://localhost:5000/user-api/orders/67fd3a992dc2c72eb6d1d6fe
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImtlbGkiLCJpYXQiOjE3NDQ2NDgzNjh9.HeMpPNpR8YUckTulNIyfUcTeGj1dIR1F6KsBdDngzkQ

###Cancel Order
PUT http://localhost:5000/user-api/users/67fd387b2dc2c72eb6d1d6fc/orders/67fd3a992dc2c72eb6d1d6fe
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im5ld191c2VyIiwiaWF0IjoxNzQzNTM1NDA1fQ.KCvoomdF20p4ilDNaISZApSuGEMX1Oave9Rzpz_YbAk

{
    "status":"Cancelled",
    "modifyTime":"{{$datetime iso8601}}"
}
###Get gallery
GET http://localhost:5000/user-api/gallery 

###Get single artwork details
GET http://localhost:5000/user-api/gallery/67fd3ea184193a23ab334b70

###Like an artwork
PUT http://localhost:5000/user-api/gallery/67fd3ea184193a23ab334b70/like
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im5ld191c2VyIiwiaWF0IjoxNzQzNTM1NDA1fQ.KCvoomdF20p4ilDNaISZApSuGEMX1Oave9Rzpz_YbAk

{
    "like": true
}


###Get all events
GET http://localhost:5000/user-api/events 


###Get event details
GET http://localhost:5000/user-api/events/67fd410084193a23ab334b75

###Get all courses
GET http://localhost:5000/user-api/courses 

###Get course details
GET http://localhost:5000/user-api/courses/67fd419b84193a23ab334b76

###Submit help request
POST http://localhost:5000/user-api/helpQueries 
Content-Type: application/json

{
    "username": "123456",
    "message": "keli's help request",
    "subject": "Account Issues",
    "timestamp": "{{$datetime iso8601}}",
    "deleted":false
}


### Add new artwork  (admin requests)
POST http://localhost:5000/admin-api/gallery  
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluX2tlbGkiLCJpYXQiOjE3NDQ2NDg0NTh9.xFoFVsuMsnKOSTnlX4A7DaAMUodkDJPaQYZIQT3hfIs

{
    "title": "Keli new art",
    "artist": "keli artist",
    "description": "Lovely keli",
    "price": 9000,
    "likes": 0,
    "deleted": false
}



### Update/Delete artwork  
PUT http://localhost:5000/admin-api/gallery/67fd3eef84193a23ab334b72  
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluX2tlbGkiLCJpYXQiOjE3NDQ2NDg0NTh9.xFoFVsuMsnKOSTnlX4A7DaAMUodkDJPaQYZIQT3hfIs

{
    "title": "super keli",
    "price": 2005,
    "deleted": false
}

### Create new event  
POST http://localhost:5000/admin-api/events  
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImtlbGkiLCJpYXQiOjE3NDQ2NDgzNjh9.HeMpPNpR8YUckTulNIyfUcTeGj1dIR1F6KsBdDngzkQ

{
    "title": "keli's event future",
    "startDate": "2025-06-15T00:00:00.000Z",
    "endDate":"2025-06-20T00:00:00.000Z",
    "location": "keli's home",
    "description": "An exclusive art event featuring keli's arts.",
    "deleted":false
}


### Update event details  
PUT http://localhost:5000/admin-api/events/67fd410084193a23ab334b75 
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImtlbGkiLCJpYXQiOjE3NDQ2NDgzNjh9.HeMpPNpR8YUckTulNIyfUcTeGj1dIR1F6KsBdDngzkQ

{
    "title": "keli's Updated event",
    "location":"Hyderabad",
    "deleted": false
}


### Create new course  
POST http://localhost:5000/admin-api/courses  
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImtlbGkiLCJpYXQiOjE3NDQ2NDgzNjh9.HeMpPNpR8YUckTulNIyfUcTeGj1dIR1F6KsBdDngzkQ

{
    "title": "keli's Techniques",
    "instructor": "keli",
    "duration": "20 weeks",
    "price": 5,
    "loaction":"keli's home",
    "mode":"Online & Offline",
    "deleted":false
}

### Update/delete course details  
PUT http://localhost:5000/admin-api/courses/67fd419b84193a23ab334b76
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImtlbGkiLCJpYXQiOjE3NDQ2NDgzNjh9.HeMpPNpR8YUckTulNIyfUcTeGj1dIR1F6KsBdDngzkQ

{
    "price": 999,
    "deleted": true
}

### Get all help queries  
GET http://localhost:5000/admin-api/helpQueries  
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImtlbGkiLCJpYXQiOjE3NDQ2NDgzNjh9.HeMpPNpR8YUckTulNIyfUcTeGj1dIR1F6KsBdDngzkQ

### Delete a help query  
PUT http://localhost:5000/admin-api/helpQueries/67fd3eeb84193a23ab334b71
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImtlbGkiLCJpYXQiOjE3NDQ2NDgzNjh9.HeMpPNpR8YUckTulNIyfUcTeGj1dIR1F6KsBdDngzkQ

{
    "deleted": true
}
 
